wlan-ap-consumer: Fixed maybe-uninitialized warning (treated as error)
```
src/lib/hostap/src/hapd.c: In function 'hapd_ctrl_cb':
src/lib/hostap/src/hapd.c:134:21: error: 'type' may be used uninitialized in this function [-Werror=maybe-uninitialized]
            } else if (!strcmp(type, EVT_FRAME_DISCONNECT)) {
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Although the 'type' should always get a value, initializing it to ""
results in an appropriate behavior even if the initial value was used.